### ISSUE TITLE
various errors when trying to start the I2C example

### ISSUE THREAD

**Issue by TheRealOtto** [flrrth/pico-bmp280#7]
Raspberry Pi Pico connected via USB and opened in Thonny. Files were unchanged and copied to the Pico.

1:   with line 4 in I2C example (from README.md) being
from bmp280 import BMP280I2C

following error is shown:
Traceback (most recent call last):
  File "stdin", line 4, in module
ImportError: can't import name BMP280I2C

2.    when changing line 4 to
from bmp280_i2c import BMP280I2C

following errors pop up:
Traceback (most recent call last):
  File "stdin", line 9, in module
  File "bmp280_i2c.py", line 13, in __init__
  File "bmp280.py", line 13, in __init__
  File "bmp280.py", line 83, in configuration
  File "bmp280.py", line 88, in reset
  File "bmp280_i2c.py", line 17, in _write
OSError: [Errno 5] EIO

Is the problem between this user's ears?
PS: brackets for stdin and module removed. Underlines for init do not show.

**Comment by drybinski** [comment]
Same problem here - does not work at all.

@TheRealOtto Did you find another solution (lib)?

**Comment by devilnest** [comment]
@TheRealOtto check address of your BMP280
Address of my device is 118 -> 0x76
To find address you can use this code:
`
hpa_i2c = machine.I2C(1, scl=machine.Pin(7), sda=machine.Pin(6), freq=200000)
bmp280_device = hpa_i2c.scan()
print(bmp280_device)

`
Note: i2c.scan() returns a List of int;

![image](https://github.com/flrrth/pico-bmp280/assets/16865180/bab3e28b-8363-4f0c-85f5-5f97357de18b)

**Comment by KonradLinkowski** [comment]
Same issue. `i2c0.scan()` returns `0x76` so I've used this address. I tried another lib but it also fails so I guess it's an issue with my setup or something
